<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <script>
    (() => {
      let x, y
      try {
        throw new Error()
      }
      catch (x) {
        // catch (e) {
        (x = 1), (y = 2)
        console.log(x) //1
      }
      console.log(x) //undefined
      console.log(y) //2
    })()
    /*
      catch接收参数x 此时x的作用域只是在catch里面 因此x=1的作用域只在catch
      外面的catch未定义
      如果x不做catch的参数 也就是catch(e)(x y之外的参数)
      输出就是 1 1 2
    */
  </script>
</body>

</html>